### PR TITLE
Like Python and R

### PR DESCRIPTION
**Pull request by floswald**
added R

### CODE REVIEW

**Comment by sglyon** [comment]
Thanks for contributing!

I think I'd put R in the Matlab and stata camp. I haven't seen people use it for general purpose programming, but I am also further removed from that community

What do others think?

**Comment by sglyon** [comment]
Ahh yes this makes sense. I didn't read carefully enough.

Thanks for clarifying. 

I think this is definitely reasonable

**Comment by floswald** [comment]
ok sounds good! I'll be using your material extensively in my course, i hope that is ok. will give credit! i'm sure you have good reasons for your choice, but the `.rst` is less fun for me than `.md` contribute, so I'm afraid I'll just comment on the notebooks at first. :-) 
thanks for the excellent work and see you around!

**Comment by arnavs** [comment]
Thanks @floswald, ended up already adding this to the notes while rewriting `:-)`. Closing now on that account (note: might take a day or two for this to be reflected in the live site, as it's pending our general reorganization of the intro lectures).

**Pull request closed without merging**
